import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { MathJaxContext } from 'better-react-mathjax'

import CalculatorPage from './CalculatorPage'
import MathJaxConfig from "../mathjax.config.json"
import { GenerateExercise } from '../scripts/QueryBackend'
import DifficultyLevel from '../classes/DifficultyLevel'
import ExercisePage from './ExercisePage.'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MathJaxContext version={3} config={MathJaxConfig}>
          <ExercisePage/>
          {/* <CalculatorPage/> */}
        </MathJaxContext>
      </main>
    </>
  )
}
