import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { MathJaxContext } from 'better-react-mathjax'

import CalculatorPage from './CalculatorPage'
import MathJaxConfig from "../mathjax.config.json"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MathJaxContext version={3} config={MathJaxConfig}>
          <CalculatorPage />
        </MathJaxContext>
      </main>
    </>
  )
}
